kind: Service
apiVersion: v1
metadata:
  name: mysql-service
  namespace: neargrocery-development
  labels:
    app: mysql
    version: "1.0"
    environment: testing
spec:
  externalIPs:
    - 192.168.99.100
  selector:
    app: mysql
    version: "1.0"
    environment: testing
  ports:
  - port: 3306
  selector:
    app: mysql

