kind: Service
apiVersion: v1
metadata:
  name: mysql-service
  namespace: insurance-development
  labels:
    app: mysql
    version: "1.0"
    environment: testing
spec:
  selector:
    app: mysql
    version: "1.0"
    environment: testing
  type: ClusterIP
  ports:
  - port: 3306
  selector:
    app: mysql

